[infinispan]
infinispan-node1 ansible_host=10.191.154.115
infinispan-node2 ansible_host=10.191.154.115

[kafka1]
kafka1 ansible_host=10.191.152.188

[kafka2]
kafka2 ansible_host=10.191.152.189

[keycloak]
keycloak-node1 ansible_host=10.191.154.108
keycloak-node2 ansible_host=10.191.154.108

[brms1]
brms1 ansible_host=10.191.154.116

[brms2]
brms2 ansible_host=10.191.154.117

[all:vars]
ansible_user=YOUR_USER
